# Generated by Django 6.1.1 on 2026-09-03 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        ('radiology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_action', models.TextField(verbose_name='الإجراء المقترح')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الخطة')),
                ('due_date', models.DateField(db_index=True, verbose_name='تاريخ الاستحقاق')),
                ('recommendation_source', models.CharField(blank=True, max_length=200, verbose_name='مصدر التوصية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'بانتظار الاعتماد'), ('active', 'نشطة'), ('overdue', 'متأخرة'), ('completed', 'مكتملة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة')], db_index=True, default='draft', max_length=30, verbose_name='حالة الخطة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_followup_plans', to=settings.AUTH_USER_MODEL, verbose_name='اعتمدها')),
                ('nodule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_plans', to='radiology.pulmonarynodule', verbose_name='العقدة الرئوية')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_plans', to='patients.patient', verbose_name='المريض')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_plans', to='core.prioritylevel', verbose_name='مستوى الأولوية')),
                ('responsible_clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_followup_plans', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب المسؤول')),
            ],
            options={
                'verbose_name': 'خطة متابعة',
                'verbose_name_plural': 'خطط المتابعة',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='ClosureDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('completed', 'اكتملت المتابعة'), ('benign', 'نتيجة حميدة'), ('referred', 'تمت الإحالة'), ('lost', 'تعذر استكمال المتابعة'), ('other', 'أخرى')], max_length=20, verbose_name='نتيجة الإغلاق')),
                ('reason', models.TextField(verbose_name='سبب الإغلاق')),
                ('closed_at', models.DateTimeField(db_index=True, verbose_name='تاريخ الإغلاق')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='الملاحظات الطبية')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_decisions', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب الذي أغلق الحالة')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closure_decision', to='followups.followupplan', verbose_name='خطة المتابعة')),
            ],
            options={
                'verbose_name': 'قرار إغلاق',
                'verbose_name_plural': 'قرارات الإغلاق',
                'ordering': ('-closed_at',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(max_length=100, verbose_name='نوع الموعد')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='التاريخ والوقت')),
                ('attendance_status', models.CharField(choices=[('scheduled', 'مجدول'), ('attended', 'حضر'), ('missed', 'لم يحضر'), ('postponed', 'مؤجل'), ('cancelled', 'ملغى')], db_index=True, default='scheduled', max_length=20, verbose_name='حالة الحضور')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء أو التأجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.healthcarefacility', verbose_name='المنشأة أو العيادة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='المريض')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='followups.followupplan', verbose_name='خطة المتابعة')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ('scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, verbose_name='الجهة المحال إليها')),
                ('reason', models.TextField(verbose_name='سبب الإحالة')),
                ('referred_at', models.DateTimeField(verbose_name='تاريخ الإحالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('accepted', 'مقبولة'), ('completed', 'مكتملة'), ('rejected', 'مرفوضة')], db_index=True, default='pending', max_length=20, verbose_name='حالة الإحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='followups.followupplan', verbose_name='خطة المتابعة')),
                ('referring_clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب المحيل')),
            ],
            options={
                'verbose_name': 'إحالة',
                'verbose_name_plural': 'الإحالات',
                'ordering': ('-referred_at',),
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(max_length=30, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التغيير')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='غيّرها')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='followups.followupplan', verbose_name='خطة المتابعة')),
            ],
            options={
                'verbose_name': 'تغير حالة',
                'verbose_name_plural': 'سجل تغيرات الحالة',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='followupplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'pending_approval', 'active', 'overdue'))), fields=('nodule',), name='one_open_followup_plan_per_nodule'),
        ),
        migrations.AddConstraint(
            model_name='followupplan',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('start_date'))), name='followup_due_date_on_or_after_start'),
        ),
    ]
