# Generated by Django 6.1.1 on 2026-09-03 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنشأة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('contact_details', models.TextField(blank=True, verbose_name='بيانات التواصل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'منشأة صحية',
                'verbose_name_plural': 'المنشآت الصحية',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='اسم المستوى')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='الرمز')),
                ('rank', models.PositiveSmallIntegerField(unique=True, verbose_name='الترتيب')),
                ('response_days', models.PositiveIntegerField(default=7, verbose_name='مدة الاستجابة بالأيام')),
                ('color', models.CharField(default='#0d766e', max_length=7, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مستوى أولوية',
                'verbose_name_plural': 'مستويات الأولوية',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_policy', models.TextField(blank=True, verbose_name='سياسة المتابعة')),
                ('escalation_days', models.PositiveIntegerField(default=7, verbose_name='مدة التصعيد بالأيام')),
                ('notification_channels', models.JSONField(blank=True, default=list, verbose_name='قنوات التنبيه')),
                ('priority_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات الأولوية')),
                ('upload_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات رفع الملفات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='core.healthcarefacility', verbose_name='المنشأة')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='نوع العملية')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='معرف العنصر')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='القيم القديمة')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='القيم الجديدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت العملية')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع العنصر')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx')],
            },
        ),
    ]
