# Generated by Django 6.1.1 on 2026-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الموظف')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='رقم التواصل')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('is_active', models.BooleanField(default=True, verbose_name='الملف نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ('user__first_name', 'user__last_name'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('permissions', models.ManyToManyField(blank=True, related_name='sanad_roles', to='auth.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ('name',),
            },
        ),
    ]
