# Generated by Django 6.1.1 on 2026-09-03 15:42

from django.db import migrations


def create_reference_data(apps, schema_editor):
    HealthcareFacility = apps.get_model("core", "HealthcareFacility")
    PriorityLevel = apps.get_model("core", "PriorityLevel")
    Role = apps.get_model("accounts", "Role")

    HealthcareFacility.objects.get_or_create(
        name="المنشأة الرئيسية",
        defaults={"city": "الرياض"},
    )
    roles = (
        ("radiologist", "طبيب أشعة"),
        ("pulmonologist", "طبيب صدرية"),
        ("followup-coordinator", "منسق متابعة"),
        ("administrative-staff", "كادر إداري"),
    )
    for code, name in roles:
        Role.objects.get_or_create(code=code, defaults={"name": name})

    priorities = (
        ("urgent", "عاجلة", 1, 1, "#d82f3f"),
        ("high", "عالية", 2, 3, "#e67e22"),
        ("normal", "عادية", 3, 7, "#1268aa"),
    )
    for code, name, rank, response_days, color in priorities:
        PriorityLevel.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "rank": rank,
                "response_days": response_days,
                "color": color,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_reference_data, migrations.RunPython.noop),
    ]
