# Generated by Django 6.1.1 on 2026-09-03 12:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_type', models.CharField(choices=[('ct', 'أشعة مقطعية'), ('xray', 'أشعة سينية'), ('pet_ct', 'PET/CT'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الأشعة')),
                ('performed_at', models.DateTimeField(db_index=True, verbose_name='تاريخ إجراء الأشعة')),
                ('report_text', models.TextField(verbose_name='نص التقرير')),
                ('report_file', models.FileField(blank=True, upload_to='radiology/reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('pdf',))], verbose_name='ملف التقرير')),
                ('indication', models.TextField(blank=True, verbose_name='سبب إجراء الأشعة')),
                ('review_status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('reviewed', 'تمت المراجعة'), ('rejected', 'تحتاج تصحيحًا')], db_index=True, default='pending', max_length=20, verbose_name='حالة المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('original_recommendation', models.TextField(blank=True, verbose_name='التوصية الأصلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_reports', to='core.healthcarefacility', verbose_name='منشأة الأشعة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_reports', to='patients.patient', verbose_name='المريض')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radiology_reports', to=settings.AUTH_USER_MODEL, verbose_name='طبيب الأشعة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_imaging_reports', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
            ],
            options={
                'verbose_name': 'تقرير أشعة',
                'verbose_name_plural': 'تقارير الأشعة',
                'ordering': ('-performed_at',),
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحليل')),
                ('model_name', models.CharField(max_length=150, verbose_name='النموذج المستخدم')),
                ('extracted_data', models.JSONField(default=dict, verbose_name='المعلومات المستخرجة')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='درجة الثقة')),
                ('supporting_text', models.TextField(blank=True, verbose_name='النصوص الداعمة')),
                ('review_status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('approved', 'معتمدة'), ('corrected', 'تم تصحيحها'), ('rejected', 'مرفوضة')], db_index=True, default='pending', max_length=20, verbose_name='حالة المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب المراجع')),
                ('imaging_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='radiology.imagingreport', verbose_name='تقرير الأشعة')),
            ],
            options={
                'verbose_name': 'تحليل ذكاء اصطناعي',
                'verbose_name_plural': 'تحليلات الذكاء الاصطناعي',
                'ordering': ('-analyzed_at',),
            },
        ),
        migrations.CreateModel(
            name='PulmonaryNodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodule_identifier', models.CharField(max_length=50, verbose_name='معرف العقدة')),
                ('lung_side', models.CharField(choices=[('right', 'اليمنى'), ('left', 'اليسرى'), ('unknown', 'غير محددة')], max_length=20, verbose_name='جهة الرئة')),
                ('lobe', models.CharField(blank=True, max_length=50, verbose_name='الفص')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('nodule_type', models.CharField(blank=True, max_length=100, verbose_name='نوع العقدة')),
                ('margin', models.CharField(blank=True, max_length=100, verbose_name='شكل الحواف')),
                ('first_detected_at', models.DateField(db_index=True, verbose_name='تاريخ أول اكتشاف')),
                ('status', models.CharField(choices=[('active', 'قيد المتابعة'), ('stable', 'مستقرة'), ('resolved', 'اختفت'), ('closed', 'مغلقة')], db_index=True, default='active', max_length=20, verbose_name='حالة العقدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pulmonary_nodules', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'عقدة رئوية',
                'verbose_name_plural': 'العقد الرئوية',
                'ordering': ('patient', 'nodule_identifier'),
            },
        ),
        migrations.CreateModel(
            name='NoduleMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_mm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحجم بالمليمتر')),
                ('volume_mm3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحجم الحجمي (مم³)')),
                ('growth_status', models.CharField(choices=[('new', 'جديدة'), ('stable', 'مستقرة'), ('increased', 'ازداد الحجم'), ('decreased', 'انخفض الحجم'), ('unknown', 'غير محدد')], default='unknown', max_length=20, verbose_name='حالة النمو')),
                ('measured_at', models.DateField(db_index=True, verbose_name='تاريخ القياس')),
                ('clinician_notes', models.TextField(blank=True, verbose_name='ملاحظات الطبيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('imaging_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodule_measurements', to='radiology.imagingreport', verbose_name='تقرير الأشعة')),
                ('nodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='radiology.pulmonarynodule', verbose_name='العقدة')),
            ],
            options={
                'verbose_name': 'قياس عقدة',
                'verbose_name_plural': 'قياسات العقد',
                'ordering': ('-measured_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='pulmonarynodule',
            constraint=models.UniqueConstraint(fields=('patient', 'nodule_identifier'), name='unique_nodule_identifier_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='nodulemeasurement',
            constraint=models.UniqueConstraint(fields=('nodule', 'imaging_report'), name='unique_nodule_measurement_per_report'),
        ),
    ]
