# Generated by Django 6.1.1 on 2026-09-03 16:36

import django.db.models.deletion
import radiology.models
import radiology.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('radiology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(blank=True, storage=radiology.storage.PrivateDicomStorage(), upload_to=radiology.models.imaging_study_upload_path, verbose_name='ملف دراسة DICOM المضغوط')),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='معرف الدراسة')),
                ('modality', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='نوع الأشعة')),
                ('study_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الدراسة')),
                ('dicom_slice_count', models.PositiveIntegerField(default=0, verbose_name='عدد شرائح DICOM')),
                ('processing_status', models.CharField(choices=[('uploaded', 'مرفوعة'), ('verifying', 'قيد التحقق'), ('ready', 'جاهزة'), ('failed', 'فشلت')], db_index=True, default='uploaded', max_length=20, verbose_name='حالة المعالجة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('imaging_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies', to='radiology.imagingreport', verbose_name='تقرير الأشعة المرتبط')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_studies', to='patients.patient', verbose_name='المريض')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_imaging_studies', to=settings.AUTH_USER_MODEL, verbose_name='رفعها')),
            ],
            options={
                'verbose_name': 'دراسة أشعة',
                'verbose_name_plural': 'دراسات الأشعة',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
