# Generated by Django 6.1.1 on 2026-09-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_imagingstudy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'بانتظار التنفيذ'), ('running', 'قيد التشغيل'), ('completed', 'مكتملة'), ('failed', 'فاشلة'), ('canceled', 'ملغاة')], db_index=True, default='queued', max_length=20, verbose_name='حالة المهمة')),
                ('model_name', models.CharField(blank=True, max_length=150, verbose_name='اسم النموذج')),
                ('model_version', models.CharField(blank=True, max_length=80, verbose_name='إصدار النموذج')),
                ('safe_error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ الآمنة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الطلب')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('imaging_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_tasks', to='radiology.imagingstudy', verbose_name='دراسة الأشعة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ai_analysis_tasks', to=settings.AUTH_USER_MODEL, verbose_name='طلبها')),
            ],
            options={
                'verbose_name': 'مهمة تحليل ذكاء اصطناعي',
                'verbose_name_plural': 'مهام تحليل الذكاء الاصطناعي',
                'ordering': ('-requested_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('imaging_study',), name='unique_active_ai_task_per_study')],
            },
        ),
    ]
