# Generated by Django 6.1.1 on 2026-09-08 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_aianalysistask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINoduleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_candidate_id', models.CharField(max_length=100, verbose_name='معرف النتيجة من النموذج')),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='درجة الثقة الأصلية')),
                ('coordinates', models.JSONField(default=dict, verbose_name='الإحداثيات الأصلية')),
                ('measurements', models.JSONField(default=dict, verbose_name='القياسات الأصلية')),
                ('original_output', models.JSONField(default=dict, verbose_name='خرج النموذج الأصلي')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت تسجيل النتيجة')),
                ('analysis_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodule_candidates', to='radiology.aianalysistask', verbose_name='مهمة التحليل')),
            ],
            options={
                'verbose_name': 'عقدة محتملة من التحليل الذكي',
                'verbose_name_plural': 'العقد المحتملة من التحليل الذكي',
                'ordering': ('analysis_task', 'source_candidate_id'),
                'constraints': [models.UniqueConstraint(fields=('analysis_task', 'source_candidate_id'), name='unique_ai_candidate_per_task')],
            },
        ),
    ]
