# Generated by Django 6.1.1 on 2026-09-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_ainodulecandidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AINoduleCandidateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'مقبولة'), ('corrected', 'مقبولة بعد التصحيح'), ('rejected', 'مرفوضة')], db_index=True, max_length=20, verbose_name='قرار الطبيب')),
                ('corrected_coordinates', models.JSONField(blank=True, default=dict, verbose_name='الإحداثيات المصححة')),
                ('corrected_measurements', models.JSONField(blank=True, default=dict, verbose_name='القياسات المصححة')),
                ('clinician_notes', models.TextField(blank=True, verbose_name='ملاحظات الطبيب')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت المراجعة')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='radiology.ainodulecandidate', verbose_name='النتيجة المحتملة')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_candidate_reviews', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب المراجع')),
            ],
            options={
                'verbose_name': 'مراجعة عقدة محتملة',
                'verbose_name_plural': 'مراجعات العقد المحتملة',
                'ordering': ('-reviewed_at',),
            },
        ),
    ]
