# Generated by Django 6.1.1 on 2026-09-20 08:57

import django.core.validators
import radiology.models
import radiology.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_ainodulecandidatereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingreport',
            name='report_file',
            field=models.FileField(blank=True, storage=radiology.storage.PrivateReportStorage(), upload_to=radiology.models.imaging_report_upload_path, validators=[django.core.validators.FileExtensionValidator(('pdf',))], verbose_name='ملف التقرير'),
        ),
    ]
