# Generated by Django 6.1.1 on 2026-09-03 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المريض')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('unspecified', 'غير محدد')], max_length=20, verbose_name='الجنس')),
                ('phone_number', models.CharField(max_length=30, verbose_name='رقم التواصل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'اتصال هاتفي'), ('sms', 'رسالة نصية'), ('email', 'بريد إلكتروني')], default='phone', max_length=20, verbose_name='وسيلة التواصل المفضلة')),
                ('record_status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('deceased', 'متوفى')], db_index=True, default='active', max_length=20, verbose_name='حالة السجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL, verbose_name='سجله')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_patients', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking_status', models.CharField(choices=[('never', 'لم يدخن'), ('former', 'مدخن سابق'), ('current', 'مدخن حالي'), ('unknown', 'غير معروف')], default='unknown', max_length=20, verbose_name='حالة التدخين')),
                ('smoking_pack_years', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='سنوات العلبة')),
                ('previous_cancer', models.BooleanField(default=False, verbose_name='سرطان سابق')),
                ('family_history', models.BooleanField(default=False, verbose_name='تاريخ عائلي')),
                ('immunosuppressed', models.BooleanField(default=False, verbose_name='ضعف المناعة')),
                ('occupational_exposures', models.TextField(blank=True, verbose_name='التعرضات المهنية')),
                ('related_symptoms', models.TextField(blank=True, verbose_name='الأعراض ذات العلاقة')),
                ('clinician_notes', models.TextField(blank=True, verbose_name='ملاحظات الطبيب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'عوامل خطورة',
                'verbose_name_plural': 'عوامل الخطورة',
            },
        ),
    ]
