# Generated by Django 6.1.1 on 2026-09-03 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followups', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم القالب')),
                ('message_type', models.CharField(choices=[('appointment', 'موعد'), ('reminder', 'تذكير'), ('escalation', 'تصعيد'), ('general', 'عام')], max_length=20, verbose_name='نوع الرسالة')),
                ('body', models.TextField(verbose_name='نص الرسالة العام والآمن')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'قالب رسالة',
                'verbose_name_plural': 'قوالب الرسائل',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('phone', 'اتصال هاتفي'), ('sms', 'رسالة نصية'), ('email', 'بريد إلكتروني'), ('other', 'أخرى')], max_length=20, verbose_name='وسيلة التواصل')),
                ('attempted_at', models.DateTimeField(db_index=True, verbose_name='تاريخ المحاولة')),
                ('result', models.CharField(choices=[('reached', 'تم التواصل'), ('no_answer', 'لا يوجد رد'), ('invalid_contact', 'بيانات التواصل غير صحيحة'), ('rescheduled', 'أعيدت الجدولة'), ('other', 'أخرى')], max_length=30, verbose_name='نتيجة المحاولة')),
                ('note', models.TextField(blank=True, verbose_name='الملاحظة')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد المحاولة التالية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_attempts', to=settings.AUTH_USER_MODEL, verbose_name='منسق المتابعة')),
                ('followup_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='followups.followupplan', verbose_name='خطة المتابعة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_attempts', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'محاولة تواصل',
                'verbose_name_plural': 'محاولات التواصل',
                'ordering': ('-attempted_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('team_alert', 'تنبيه للفريق'), ('patient_reminder', 'تذكير للمريض'), ('overdue', 'تأخر متابعة'), ('escalation', 'تصعيد')], max_length=30, verbose_name='نوع التنبيه')),
                ('recipient', models.CharField(max_length=255, verbose_name='المستلم')),
                ('channel', models.CharField(choices=[('in_app', 'داخل النظام'), ('sms', 'رسالة نصية'), ('email', 'بريد إلكتروني'), ('phone', 'اتصال هاتفي')], max_length=20, verbose_name='قناة الإرسال')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='وقت الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال الفعلي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('failed', 'فشل'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=20, verbose_name='حالة الإرسال')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], db_index=True, default='normal', max_length=20, verbose_name='درجة الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='followups.appointment', verbose_name='الموعد')),
                ('followup_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='followups.followupplan', verbose_name='خطة المتابعة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='patients.patient', verbose_name='المريض')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanad_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستلم')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.messagetemplate', verbose_name='قالب الرسالة')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ('scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت المحاولة')),
                ('was_successful', models.BooleanField(default=False, verbose_name='نجحت المحاولة')),
                ('provider_reference', models.CharField(blank=True, max_length=255, verbose_name='مرجع مزود الخدمة')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب الفشل')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notification', verbose_name='التنبيه')),
            ],
            options={
                'verbose_name': 'محاولة إرسال',
                'verbose_name_plural': 'سجل محاولات الإرسال',
                'ordering': ('-attempted_at',),
            },
        ),
    ]
