# Generated by Django 6.1.1 on 2026-09-03 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
        ('notifications', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', True), ('notification_type__in', ('overdue', 'escalation'))), fields=('followup_plan', 'notification_type'), name='unique_plan_automation_alert'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('appointment', 'notification_type', 'channel', 'scheduled_at'), name='unique_appointment_reminder'),
        ),
    ]
